apiVersion: v1
kind: Pod
metadata:
    name: ip-app-cm
spec:
  containers:
  - name: ip-app
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      valueFrom:
          configMapKeyRef:
              name: my-cm
              key: env
    - name: APP
      valueFrom:
          configMapKeyRef:
              name: my-cm
              key: app 