apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
      containers:
      - name: ipapp
        image: jayanthhl/kube:latest
        ports:
        - containerPort: 8080
